import type { Metadata } from "next";
import { Alata } from "next/font/google";
import "./globals.css";

const alata = Alata({
  subsets: ["latin"],
    weight: ["400"],
    style: ["normal"],
});

export const metadata: Metadata = {
  title: "Ignite Idea",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${alata.className} antialiased`}
      >
          {children}
      </body>
    </html>
  );
}
